# Why NumPy?
NumPy is the main package for scientific computations in python and has been a major backbone of Python applications in various computational, engineering, scientific, statistical, image processing, etc fields.

In [14]:
import numpy as np #always remember to import numpy
import time
t0 = time.process_time()
print(t0)

0.5625


In [15]:
tmatrix1 = [1,2,3]
#array2
tmatrix2 = [1,2,3]
#dot matrix
np.dot(tmatrix1,tmatrix2)

14

In [16]:
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)

array([[37, 40],
       [85, 92]])

In [17]:
#print array type
print(type(a))

<class 'numpy.ndarray'>


In [18]:
#print array shape
print(a.shape)

(2, 2)


In [21]:
#print smallest number in a matrix
print(a.min())

#print biggest number
print(a.max())


1
4


In [23]:
#Adding, subtracting and multiplying
#array1
mmatrix1 = np.array([[1,2,3],[4,5,6]])
#array2
mmatrix2 = np.array([[6,7,8],[8,9,10]])
#add matrices
addmatrix = np.add(mmatrix1,mmatrix2)
print('addmatrix \n', addmatrix)
#subtract matrices
submatrix = np.subtract(mmatrix1,mmatrix2)
print('submatrix \n', submatrix)
#multiply matrices
mulmatrix = np.multiply(mmatrix1,mmatrix2)
print('mulmatrix \n', mulmatrix)

addmatrix 
 [[ 7  9 11]
 [12 14 16]]
submatrix 
 [[-5 -5 -5]
 [-4 -4 -4]]
mulmatrix 
 [[ 6 14 24]
 [32 45 60]]


In [24]:
#Calculating dot products
#array1
dmatrix1 = np.array([[1,2,3],[4,5,6]])
#array2
dmatrix2 = np.array([[6,7],[8,9],[9,10]])
print('array1 \n', dmatrix1)
print('array2 \n', dmatrix2)
#dot matrix
dotmatrix = np.dot(dmatrix1,dmatrix2)
print('dotmatrix \n', dotmatrix)

array1 
 [[1 2 3]
 [4 5 6]]
array2 
 [[ 6  7]
 [ 8  9]
 [ 9 10]]
dotmatrix 
 [[ 49  55]
 [118 133]]


In [27]:
#Finding the exponential of a matrix
mmatrix1 = np.array([[1,2,3],[4,5,6]])
mexp = np.exp(mmatrix1)
print(mexp)

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [28]:
#print variance of a matrix
mmatrix= np.array([[1,2,3],[4,5,6]])
print(np.var(mmatrix))
output:2.9166666666666665
#print mean of a matrix
print(np.mean(mmatrix))
output:3.5
#print standard deviation of a matrix
print(np.std(mmatrix))
output:1.707825127659933

2.9166666666666665
3.5
1.707825127659933


# Reshaping Arrays

In [29]:
mmatrix= np.array([[1,2,3],[4,5,6]])
rematrix = mmatrix.reshape(3,2)
print(rematrix.shape)
output:(3, 2)
#flatten mmatrix to 1-d array
flmatrix = mmatrix.flatten()
print(flmatrix)

(3, 2)
[1 2 3 4 5 6]


# The Sigmoid Activation Function
Using a mathematical definition, the sigmoid function takes any range real number and returns the output value which falls in the range of 0 to 1.

In [30]:
#sigmoid function
def sigmoid(X):
   return 1/(1+np.exp(-X))

In [31]:
sigmoid(mmatrix)

array([[0.73105858, 0.88079708, 0.95257413],
       [0.98201379, 0.99330715, 0.99752738]])

#  ReLu
The Rectified linear unit (ReLu) activation function has been the most widely used activation function for deep learning applications with state-of-the-art results. 

In [32]:
def relu(X):
   return np.maximum(0,X)

In [33]:
relu(mmatrix)

array([[1, 2, 3],
       [4, 5, 6]])

# The Softmax Function
The Softmax function is used for prediction in multi-class models where it returns probabilities of each class in a group of different classes, with the target class having the highest probability.

In [34]:
def softmax(X):
    expo = np.exp(X)
    expo_sum = np.sum(np.exp(X))
    return expo/expo_sum

In [35]:
print (softmax(mmatrix))

[[0.00426978 0.01160646 0.03154963]
 [0.08576079 0.23312201 0.63369132]]
