In [27]:
import torch

In [28]:
def activation(x):
    return 1/(1+torch.exp(-x))

# Generating some fake data

In [29]:
features = torch.randn(1,5)
print(features)
weights = torch.randn_like(features)
print(weights)
bias=torch.randn(1,1)
print(bias)

tensor([[ 0.2499,  0.6793, -0.3324, -0.5582,  1.5116]])
tensor([[-0.5100, -0.2874, -0.3099,  0.0325, -0.7962]])
tensor([[1.0500]])


In [30]:
data =torch.sum(features*weights)+bias
print(data)


tensor([[-0.3913]])


In [31]:
y = activation(data)
print(y)

tensor([[0.4034]])


# Matrix Multiplication
mm => Matrix multiplication is most simple and most strict about the tensor that you pass
matmul=>Its actually supoort broadcasting

In [32]:
#weights.reshape(5,1)

In [33]:
#weights.view(5,1)

In [39]:
data =torch.mm(features,weights.view(5,1))+bias

In [40]:
print(activation(data))

tensor([[0.4034]])
